apiVersion: batch/v1
kind: Job
metadata:
  name: update-products-job
spec:
  template:
    spec:
      containers:
        - name: update-products-job
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              curl -X PATCH "http://api-gateway:8080/productservice/products" -H "accept: */*" -H "Content-Type: application/json" \
                   -d "{ \"name\": \"Guerra e Pace\", \"stockLevelVariation\": \"-2\" }"
              echo 
              
              curl -X PATCH "http://api-gateway:8080/productservice/products" -H "accept: */*" -H "Content-Type: application/json" \
                   -d "{ \"name\": \"Anna Karenina\", \"stockLevelVariation\": \"2\" }"
              echo 
              
              curl -X PATCH "http://api-gateway:8080/productservice/products" -H "accept: */*" -H "Content-Type: application/json" \
                   -d "{ \"name\": \"I promessi sposi\", \"stockLevelVariation\": \"-1\" }"
              echo
      restartPolicy: Never
  backoffLimit: 4