apiVersion: batch/v1
kind: Job
metadata:
  name: validate-orders
spec:
  template:
    spec:
      containers:
        - name: validate-orders
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "# convalida l'ordine 1"
              echo $(curl -s http://api-gateway:8080/ordervalidationservice/ordervalidations/1)
              echo
              echo "# convalida l'ordine 2"
              echo $(curl -s http://api-gateway:8080/ordervalidationservice/ordervalidations/2)
              echo
              echo "# convalida l'ordine 3"
              echo $(curl -s http://api-gateway:8080/ordervalidationservice/ordervalidations/3)
              echo
      restartPolicy: Never
  backoffLimit: 4