apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-validation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-validation-service
  template:
    metadata:
      labels:
        app: order-validation-service
    spec:
      containers:
        - name: order-validation-service
          image: haowe/asw-ordermanager:order-validation-service-1.3
---
apiVersion: v1
kind: Service
metadata:
  name: order-validation-service
spec:
  type: NodePort
  selector:
    app: order-validation-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083